version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '139:139'
      - '445:445'
    volumes:
      - '/home/mdelgert/shared:/shared'
    environment:
      USERNAME: 'mdelgert'
      PASSWORD: 'password'

# $ docker-compose up --build -d
# $ docker-compose down