# https://github.com/linuxserver/docker-webtop
# https://docs.linuxserver.io/images/docker-webtop

version: "2.1"
services:
  webtop:
    #image: lscr.io/linuxserver/webtop:latest
    #image: lscr.io/linuxserver/webtop:alpine-kde
    image: lscr.io/linuxserver/webtop:ubuntu-kde
    container_name: webtop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    volumes:
      - /home/mdelgert/webtop:/config
      #- /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 8083:3000
      - 3001:3001
    devices:
      - /dev/dri:/dev/dri #optional
    shm_size: "1gb" #optional
    restart: unless-stopped
    
# docker compose up -d