version: '3'
services:
  ubuntu1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '2022:22'
    environment:
      USERNAME: 'mdelgert'
      PASSWORD: 'password'  
    restart: unless-stopped

# docker compose up --build -d
# docker compose down