version: '3'

services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes:
      - /portainer/Files/AppData/Config/vaultwarden:/data/
    ports:
      - 2000:80
      #- 2001:443
    environment:
      DOMAIN: "https://vw.vessea.com"
      # DATABASE_URL: "postgresql://user_name:user_password@db_host:5432/vaultwarden"
      # DISABLE_ADMIN_TOKEN: true
      # ADMIN_TOKEN: "Vy2VyYTTsKPv8W5aEOWUbB/Bt3DEKePbHmI4m9VcemUMS2rEviDowNAFqYi1xjmp" #To disable admin page, make sure no ADMIN_TOKEN environment variable is set, and no "admin_token" key exists in config.json
      # SENDS_ALLOWED: true
      # SIGNUPS_ALLOWED: true
      # SIGNUPS_VERIFY: false
      # SIGNUPS_VERIFY_RESEND_TIME: 3600
      # SIGNUPS_VERIFY_RESEND_LIMIT: 6
      # EMERGENCY_ACCESS_ALLOWED: true
      # SIGNUPS_DOMAINS_WHITELIST: "example.com,example.net,example.org"

# docker compose down
# docker compose up -d