# https://www.techaddressed.com/tutorials/vaultwarden-docker-compose/
# https://medium.com/swlh/set-up-your-own-personal-password-vault-313d76374046
# https://hub.docker.com/r/vaultwarden/server
# https://www.howtoforge.com/how-to-install-vaultwarden-on-ubuntu-22-04/
# https://docs.cloud68.co/books/instances-faqs/page/vaultwarden

version: '3'

services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes:
      - /home/mdelgert/data:/data/
    ports:
      - 2000:80
      #- 2001:443
    environment:
      - DOMAIN=https://test1.vessea.com
      - LOGIN_RATELIMIT_MAX_BURST=10
      - LOGIN_RATELIMIT_SECONDS=60
      - ADMIN_RATELIMIT_MAX_BURST=10
      - ADMIN_RATELIMIT_SECONDS=60
      - ADMIN_TOKEN=password
      - SENDS_ALLOWED=true
      - EMERGENCY_ACCESS_ALLOWED=true
      - WEB_VAULT_ENABLED=true
      # - SIGNUPS_ALLOWED=false
      # - SIGNUPS_VERIFY=true
      # - SIGNUPS_VERIFY_RESEND_TIME=3600
      # - SIGNUPS_VERIFY_RESEND_LIMIT=5
      # - SIGNUPS_DOMAINS_WHITELIST=yourdomainhere.com,anotherdomain.com
      # - SMTP_HOST=smtp.youremaildomain.com
      # - SMTP_FROM=vaultwarden@youremaildomain.com
      # - SMTP_FROM_NAME=Vaultwarden
      # - SMTP_SECURITY=SECURITYMETHOD
      # - SMTP_PORT=XXXX
      # - SMTP_USERNAME=vaultwarden@youremaildomain.com
      # - SMTP_PASSWORD=YourReallyStrongPasswordHere
      # - SMTP_AUTH_MECHANISM="Mechanism"

# docker compose up
# docker compose up -d
# docker compose down      