version: '3'

services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes:
      - /portainer/Files/AppData/Config/vaultwarden:/data/
    ports:
      - 2000:80
      #- 2001:443
    environment:
      DOMAIN: "https://vw.vessea.com"
      #DATABASE_URL: "postgresql://root:password@b1:5432/vaultwarden"
      # DISABLE_ADMIN_TOKEN: true
      ADMIN_TOKEN: "GTZeHKioc3qyhSxAPA!WU7SZZ9" #To disable admin page, make sure no ADMIN_TOKEN environment variable is set, and no "admin_token" key exists in config.json
      # SENDS_ALLOWED: true
      # SIGNUPS_ALLOWED: true
      # SIGNUPS_VERIFY: false
      # SIGNUPS_VERIFY_RESEND_TIME: 3600
      # SIGNUPS_VERIFY_RESEND_LIMIT: 6
      # EMERGENCY_ACCESS_ALLOWED: true
      # SIGNUPS_DOMAINS_WHITELIST: "example.com,example.net,example.org"

# docker compose down
# docker compose up -d