version: '3'
services:
  samba:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: samba
    hostname: samba
    network_mode: bridge
    restart: unless-stopped
    ports:
      - '139:139'
      - '445:445'
    volumes:
      - '/home/mdelgert/shared:/shared'
    environment:
      USERNAME: 'mdelgert'
      PASSWORD: 'password'

# $ docker compose up --build -d
# $ docker compose down