version: '3'
services:
  samba:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: mdelgert/alpine-samba:latest
    container_name: samba
    hostname: samba
    network_mode: bridge
    restart: unless-stopped
    ports:
      - '139:139'
      - '445:445'
    volumes:
      - '/mnt/d1:/d1'
      - '/mnt/d2:/d2'
    environment:
      USERNAME: 'mdelgert'
      PASSWORD: 'password'

# $ docker compose up --build -d
# $ docker compose up -d
# $ docker compose down

# Icon - https://cdn2.iconfinder.com/data/icons/kids/128x128/apps/samba.png