version: '3'
services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx
    hostname: nginx
    network_mode: bridge
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - data:/data
      - data:/etc/letsencrypt
volumes:
  data:

# docker compose up -d
# docker compose down

# Links
# https://notthebe.ee/blog/easy-ssl-in-homelab-dns01/
# https://www.duckdns.org/domains
# https://dash.cloudflare.com/
# https://nginxproxymanager.com/
# https://stackoverflow.com/questions/37705017/create-named-docker-volume-with-docker-compose
# https://nginxproxymanager.com/logo.png