# Use the Alpine Linux base image
FROM alpine:3.18

# Install OpenSSH server
RUN apk update && apk upgrade && \
    apk add --no-cache openssh

# Set root password as a build argument
ARG ROOT_PASSWORD

# Enable root login and set the root password
RUN echo "root:${ROOT_PASSWORD}" | chpasswd

# Generate SSH host keys
RUN ssh-keygen -A

# Expose SSH port
EXPOSE 22

# Start the SSH server
CMD ["/usr/sbin/sshd", "-D"]

# docker build -t alpine-ssh --build-arg ROOT_PASSWORD=password .
# docker run -d -p 2022:22 -e ROOT_PASSWORD=password alpine-ssh
# docker run -d -p 2022:22 alpine-ssh
# ssh root@localhost -p 2022




