# Icon - https://cdn2.iconfinder.com/data/icons/kids/128x128/apps/samba.png
# https://hub.docker.com/repository/docker/mdelgert/samba-server/general

version: '3'
services:
  alpine-samba:
    container_name: alpine-samba
    image: mdelgert/alpine-samba:latest
    ports:
      - '139:139'
      - '445:445'
    volumes:
      - '/home/mdelgert/shared:/shared'
    environment:
      USERNAME: 'mdelgert'
      PASSWORD: 'password'
    restart: unless-stopped
