# Icon : https://www.gravatar.com/avatar/f6ebd1a2056ef8d3fdd354e7c74e52fe?s=120&r=g&d=404

version: '3'
services:
  alpine-sshd:
    container_name: alpine-sshd
    image: mdelgert/alpine-sshd:latest
    ports:
      - '2021:22'
    environment:
      USERNAME: 'mdelgert'
      PASSWORD: 'password'
    restart: unless-stopped