# Icon - https://cdn2.iconfinder.com/data/icons/kids/128x128/apps/samba.png
# https://hub.docker.com/repository/docker/mdelgert/samba-server/general

version: '3'
services:
  alpine:
    container_name: alpine
    image: mdelgert/alpine-sshd:latest
    ports:
      - '2021:22'
    environment:
      USERNAME: 'mdelgert'
      PASSWORD: 'password'
    restart: unless-stopped
