# https://stackoverflow.com/questions/71658362/azure-sql-edge-does-not-persist-data-to-docker-volumes

version: '3'
services:
  azure-sql:
    image: "mcr.microsoft.com/azure-sql-edge"
    hostname: "azure-sql"
    environment:
      ACCEPT_EULA: 1
      MSSQL_SA_PASSWORD: ":8jNZdK7cK"
      MSSQL_USER: "SA"
      MSSQL_PID: "Developer"
    volumes:
      - azure-sql-storage:/var/opt/mssql-extensibility/data
      - azure-sql-storage:/var/opt/mssql-extensibility/log
      - azure-sql-storage:/var/opt/mssql-extensibility
    ports:
      - "1433:1433"

volumes:
  azure-sql-storage:
    external: true